# Created by Noor Ameen,
# Join on linkedin https://www.linkedin.com/in/noor-ameen/
# join me on github.com https://github.com/calltech
---
- hosts: servers
  become: yes
  gather_facts: true
  remote_user: user1
  tasks:
    # - name: delete something
    #   raw: rm -rf /var/lib/docker
    # - name: start docker service
    #   raw: systemctl start docker
    # Initilize kubernetes cluster with kubeadm init
    # - name: instruct Kubeadm to ignore preflight check for Docker validation
    #   command: sudo kubeadm init --ignore-preflight-errors=SystemVerification
    #--ignore-preflight-errors=SystemVerification
    - name: initialize the cluster
      shell: kubeadm init --ignore-preflight-errors=SystemVerification  --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
    # Create .kube directory in user home
    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    # Compy admin.conf file form /etc/kubernetes to home/user/.kube
    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/root/.kube/config
        remote_src: yes
        owner: user1

    # Initialize pod network with flannel
    - name: install Pod network
      become: yes
      become_user: user1
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

    # Get master node join token
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
    # Set join command
    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
