# Created by Noor Ameen,
# Join on linkedin https://www.linkedin.com/in/noor-ameen/
# join me on github.com https://github.com/calltech

---
- hosts: master
  become: yes
  remote_user: user1
  become_method: sudo
  gather_facts: true

  vars:
  # vars here

  tasks:
    # Remove swap line from fstab
    - name: Remove swap from fsab
      lineinfile:
        destfile: /etc/fstab
        regexp: "swap"
        state: absent
      register: swap
    #master swapoff -a
    - name: Swapoff -a
      become: yes
      shell: sudo swapoff -a

    # - name: install python
    #   apt:
    #     name: python2
    #     state: present
    # Run ap-get update if past 3600 seconds
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # sudo apt-get update
    - name: Run apt-get updates ...
      apt:
        update_cache: yes

    # Installing python2.7 on all target machines
    - name: Install python2
      apt:
        name: python
        state: present

    # Adding gpg key for docker-ce
    - name: Add Docker GPG Key Docker
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    # Adding Repository key for Docker CE
    - name: Add Docker APT Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

    # Running updates before docker installation
    - name: Run updates before docker installations
      apt:
        update_cache: yes
    # Installing all required toold for docker ce
    - name: Install List of Docker-ce packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - docker-ce

    # Installing Kubernetes, Kubeadm, Kubelet and kubectl
    - name: Running apt-get update
      apt:
        update_cache: yes

    # Installing kubernetes pre-requisits apt-transport-https
    - name: Installing apt-transport-https now!
      apt:
        name: apt-transport-https
        state: present

    # Adding GPG key for kubernetes
    - name: Add Docker GPG Key for Kubernetes
      apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg

    # Adding Kubernetes repo
    - name: Adding Kubernetes Repository Now!
      raw: sudo apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"

    # Running updates after adding Kubernetes Repository
    - name: Running updates after adding Kubernetes repository
      apt:
        update_cache: yes

    # Installing Kubernetes, kubeadm, kebelet, kubectl
    - name: Installing Kubernetes, Kubeadm, kubelet and kubectl
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - kubeadm
        - kubectl
        - kubelet
