- hosts: web
  become: yes
  tasks:
    # Create a non-root user (user1)
    - name: create the 'user1' user
      user: name=user1 append=yes state=present createhome=yes shell=/bin/bash

    # Allow user to have passwordless sudo access
    - name: allow 'user1' to have sudo access
      lineinfile:
        dest: /etc/sudoers
        line: "ubuntu ALL=(ALL) NOPASSWD: ALL"
        validate: "visudo -cf %s"

    # setup authorize key for user1
    - name: set up authorized keys for the user1 user
      authorized_key: user=user1 key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
